### ISSUE TITLE
[SAX2Java binding] Error handling of XML parsing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lahirue/jlibs#3]
```
When this is used:
handler.setIgnoreUnresolved(false);

SAX2Java binding raise this exception:

Exception in thread "main" java.lang.NullPointerException
        at jlibs.xml.sax.binding.impl.Handler$BindingContext.xpath
(Handler.java:218)
        at jlibs.xml.sax.binding.SAXContext.toString(SAXContext.java:129)
        at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2794)

instead of

org.xml.sax.SAXException: can't find binding for /employee/email (line=5, 
col=12)

Tested in R664 with not bounded elements and with bounded elements that 
contain XML code with missing CDATA blok like this:

<aktualni-zmeny><span style="color:red;">28.1. do 13 h, 29.1. ZAVŘENO-
STĚHOVÁNÍ</span></aktualni-zmeny>
```

Original issue reported on code.google.com by `tomas.pr...@gmail.com` on 29 Jan 2010 at 11:34

**Comment by GoogleCodeExporter** [comment]
```
[FIXED]

revision 666 (R666)
```

Original comment by `santhosh.tekuri@gmail.com` on 29 Jan 2010 at 3:41
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks. It works already.

But I have one question. Problem of this solution is that every error in XML 
completely 
stop binding process. I need only need log unexpected element as warning, or 
send some 
mail, but I need continue in importing process. Is this possible?
```

Original comment by `tomas.pr...@gmail.com` on 29 Jan 2010 at 8:05

**Comment by GoogleCodeExporter** [comment]
```
[FIXED] R667

getIgnoreUnresolved() and setIgnoreUnresolved(boolean) methods are removed.

now you can do:

bindingHandler.setBindingListener(new BindingListener(){
    @Override
    public void unresolvedElement(SAXContext<?> context) throws SAXException{
        String xpath = context.xpath();
        int line = context.locator().getLineNumber();
        int column = context.locator().getColumnNumber();
        // now you can either log the information or throw SAXException to stop
        // binding process
    }
});
```

Original comment by `santhosh.tekuri@gmail.com` on 30 Jan 2010 at 2:54

**Comment by GoogleCodeExporter** [comment]
```
Great! This is best solution! Thanks you very much.
Especially that line number and column is available. I used standard SAX which 
is 
available in standard JDK and I can't obtain line number and column number.
```

Original comment by `tomas.pr...@gmail.com` on 30 Jan 2010 at 8:41
